### ISSUE TITLE
Точно int? И почему умножается на два (это должно делаться в расчёте периметра, а не здесь)?

### ISSUE THREAD

**Issue by coursar** [Roman-code37/WallpaperCalculator#3]
https://github.com/Roman-code37/WallpaperCalculator/blob/9bb319da9208058e8b3b7c7668b6a25fc15157ae/src/Main.java#L3-L4

**Comment by Roman-code37** [comment]
@coursar комната прямоугольная, соответственно 2 стены по 5 метров, 2 стены по 3 метра

**Comment by coursar** [comment]
Переменная называется length, т.е. должна содержать длину (а не две длины).

**Comment by Roman-code37** [comment]
int исправлен на byte
