### ISSUE TITLE
Чем отличается просто от length?

### ISSUE THREAD

**Issue by coursar** [Roman-code37/WallpaperCalculator#4]
https://github.com/Roman-code37/WallpaperCalculator/blob/9bb319da9208058e8b3b7c7668b6a25fc15157ae/src/Main.java#L7

**Comment by Roman-code37** [comment]
просто length это длина стены комнаты, а length2 это длина рулона. не сразу сообразил как назвать эту переменную

**Comment by coursar** [comment]
Назовите rollLength
